name: Release Please

on:
  push:
    branches:
      - main
      - "*.x.x"
      - "*.*.x"
  workflow_dispatch:

jobs:
  release-please:
    timeout-minutes: 1
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: googleapis/release-please-action@v4
        with:
          target-branch: ${{ github.ref_name }}
